ad_integration.settings:
  type: mapping
  label: 'Ad integration settings'
  mapping:
    ad_provider:
      type: string
      label: 'Ad provider'
    adsc_container_tag:
      type: string
      label: 'Container tag url'
    adsc_ad_engine:
      type: string
      label: 'Container ad engine'
